package org.letsconfide.platform;

import org.letsconfide.LetsConfideCloseable;

/**
 * Represents security device such as a TPM (Trusted Platform Module).
 */
public interface SecurityDevice extends LetsConfideCloseable
{

    /**
     * Wraps the given data encryption key.
     * @param dek The data encryption key
     * @return the wrapped key
     */
    byte[] wrap(byte[] dek);

    /**
     * Unwraps the given encrypted data encryption key.
     * Inverse of {@link #wrap(byte[])}
     * @param encryptedDek The encrypted data encryption key
     * @return the key
     */
    byte[] unwrap(byte[] encryptedDek);

    /**
     * Wraps the given ephemeral data encryption key.
     * @param dek The data encryption key
     * @return the wrapped key
     */
    byte[] wrapEphemeral(byte[] dek);

    /**
     * Unwraps the given ephemeral, encrypted data encryption key.
     * @param encryptedDek The wrapped key
     * @return the key
     */
    byte[] unwrapEphemeral(byte[] encryptedDek);

    /**
     * Generates an array of random bytes.
     * @param size number of bytes needed
     * @return the generated bytes
     */
    byte[] getRandomBytes(int size);



}
